#!/bin/bash
set -e

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd $SELF_DIR

buildapp() {
	mkdir -p $APP
	cp ../src/*.lua "$APP"
	cp ../assets/* "$APP"
	zip -j "$TMP"/app.love "$APP"/*
}

buildlove() {
	mkdir -p "$TARGET"/runtime
	cp -r "$ARCH"/love/* "$TARGET"/runtime
	cp -r "$ARCH"/base/* "$TARGET"
	cat "$TARGET"/love.exe "$TMP"/app.love >"$TARGET"/app.exe
	cat "$TARGET"/lovec.exe "$TMP"/app.love >"$TARGET"/appc.exe
	rm "$TARGET"/love.exe "$TARGET"/lovec.exe
	mv "$TARGET"/app.exe "$TARGET"/love.exe
	mv "$TARGET"/appc.exe "$TARGET"/lovec.exe
}

case "$1" in
	x64 | x86)
		ARCH="$1"
		TARGET=../build/windows/"$ARCH"/polyamory
		[ -d "$1" ] || { echo "ERROR: run build from the 'windows' directory"; exit 1; }
		;;
	*)
		echo "usage: $0 x64 | x86"
		exit 1
		;;
esac

TMP=$(mktemp -d) || exit 1
APP="$TMP/app"

buildapp
buildlove
echo Done! polyamory built in "$TARGET"
